FROM maven:3.8.6-amazoncorretto-17 AS builder
ADD ./pom.xml pom.xml
RUN mvn dependency:resolve

ADD ./src src/
RUN mvn clean package

FROM tomcat:9.0.53-jdk17-corretto
COPY --from=builder target/login-1.0-SNAPSHOT.war /usr/local/tomcat/webapps/servlet.war

EXPOSE 8080
