version: "3"

services:

  postgres:
    image: "postgres:13.4-alpine"
    container_name: "message-service"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "messages"
    ports:
      - "15432:5432"