server:
  port: 8080

feign:
  client:
    config:
      domain:
          connectTimeout: 5000
          readTimeout: 3000

services:
  main:
    url: 'http://localhost:8081'
  message:
    url: 'http://localhost:8082'
