server:
  port: 9090

feign:
  client:
    config:
      domain:
        connectTimeout: 5000
        readTimeout: 3000

jwt:
  secret: "hello@world!"

services:
  users-service:
    url: 'http://localhost:9091'
  message-service:
    url: 'http://localhost:9092'
