name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Standard Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - run: mvn -f ${GITHUB_REF##*/}/pom.xml clean verify
      - run: mvn -f ${GITHUB_REF##*/}/pom.xml clean package
          
